name: ds_delivery
description: App de delivery simples, funcional e inteligente.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design e Material 3
  dynamic_color: ^1.7.0
  flutter_svg: ^2.0.10

  # Internacionalização
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Estado
  flutter_riverpod: ^2.6.1

  # Navegação
  go_router: ^14.1.1

  # Responsividade
  flutter_screenutil: ^5.9.0

  # HTTP
  dio: ^5.4.3+1

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.9
  flutter_local_notifications: ^17.1.2
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.3.2+9

  # Geolocalização e Mapas
  google_maps_flutter: ^2.5.3
  flutter_google_places_sdk: ^0.3.7
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  latlong2: ^0.9.0
  
  # Implementação customizada
  google_maps_webservice: ^0.0.19
  google_place: ^0.4.7
  flutter_typeahead: ^5.0.1
  uuid: ^4.5.0
  flutter_polyline_points: ^2.0.0

  # Splash e animações
  flutter_native_splash: ^2.4.0
  flutter_animate: ^4.5.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  material_symbols_icons: ^4.2719.0

  video_player: ^2.7.2
  image_picker: ^1.1.0
  image_cropper: ^9.1.0
  page_transition: ^2.2.1
  logging: ^1.3.0
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  url_launcher: ^6.1.10

# Isso força todas as dependências a usar a versão do http especificada
dependency_overrides:
  http: ^0.13.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

flutter:
  assets:
    - assets/images/
    - assets/icon/
    - assets/videos/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 100
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 200
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 300
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 500
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 600
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 700
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 800
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 900

    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 100
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 200
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 800
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
          weight: 900