// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtqCouzAf6RAlPs9f0JKeFnpwYJWombCQ',
    appId: '1:342509724801:web:b4a61d21701bb225e9d980',
    messagingSenderId: '342509724801',
    projectId: 'dsdelivery-v1',
    authDomain: 'dsdelivery-v1.firebaseapp.com',
    storageBucket: 'dsdelivery-v1.firebasestorage.app',
    measurementId: 'G-G90RW95B4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm60xTO4OMfaZx2aT1emWTMKQz9Sn3E-Y',
    appId: '1:342509724801:android:cab13153ec5ca227e9d980',
    messagingSenderId: '342509724801',
    projectId: 'dsdelivery-v1',
    storageBucket: 'dsdelivery-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAstItJel6KK5etnD4JPlVstAV4MKSBVRg',
    appId: '1:342509724801:ios:e22d287fd6cbccf0e9d980',
    messagingSenderId: '342509724801',
    projectId: 'dsdelivery-v1',
    storageBucket: 'dsdelivery-v1.firebasestorage.app',
    iosClientId: '342509724801-051agq6qfmae1fu78r6msn3u7ufq3m8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.dsDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAstItJel6KK5etnD4JPlVstAV4MKSBVRg',
    appId: '1:342509724801:ios:e22d287fd6cbccf0e9d980',
    messagingSenderId: '342509724801',
    projectId: 'dsdelivery-v1',
    storageBucket: 'dsdelivery-v1.firebasestorage.app',
    iosClientId: '342509724801-051agq6qfmae1fu78r6msn3u7ufq3m8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.dsDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtqCouzAf6RAlPs9f0JKeFnpwYJWombCQ',
    appId: '1:342509724801:web:82f9b57631a5f040e9d980',
    messagingSenderId: '342509724801',
    projectId: 'dsdelivery-v1',
    authDomain: 'dsdelivery-v1.firebaseapp.com',
    storageBucket: 'dsdelivery-v1.firebasestorage.app',
    measurementId: 'G-RJCWTVP2Y5',
  );
}
